training:
  precision_in: highest
  batch_size: 1
  epochs: 100
  lr: 3e-4
  checkpoint_path: #/home/tkhan/bfm-finetune/outputs/2025-07-09/16-33-12/checkpoints/ #/projects/prjs1134/data/projects/biodt/storage/weights/finetune #TODO Add your checkpoint path here in the folder level e.g. /home/atrantas/bfm-finetune/bfm_finetune/outputs_bfm_finetune_48800/checkpoints/
  val_every: 5
  backend: fsdp #ddp
  gpus: 0 # for multi-gpu runs
  gpu: 0 # for single-gpu runs


dataset:
  toy: False
  num_species: 500 # can set here top k species
  num_workers: 15
  negative_lon_mode: ignore # roll, exclude, translate, ignore (breaks aurora if supersampling is No)

model:
  hidden_dim: 160
  supersampling:
    enabled: Yes # Yes / No
    target_region: # if enabled, target_region is used, otherwise the original data region is used
      min_lon: 0
      max_lon: 360
      min_lat: -90
      max_lat: 90
  base_small: False
  big: True
  big_ft: False
